version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8087:8080"
  testing:
    build:
      context: ../..
      dockerfile: helpers/drush-alias/testing/Dockerfile
    environment:
      # Make sure to run lagoon with properly configured hiera repo
      # otherwise the script will not find any data for the sitegroup
      - LAGOON_OVERRIDE_PROJECT=ci-drupal
      - LAGOON_OVERRIDE_ENDPOINT=192.168.99.1:2020
      - LAGOON_OVERRIDE_API_ENDPOINT=http://api:3000/graphql
      - LAGOON_DEBUG=true
      #- LAGOON_IGNORE_DRUSHCACHE=true
    volumes:
      - './web/aliases.drushrc.php.stub:/etc/drush/aliases.drushrc.php.stub'
    networks:
      - lagoon_default
networks:
  lagoon_default:
    external: true
